[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "precomputed-annotation-indices"
version = "0.1.0"
dependencies = [
    "numpy",
    "psutil>=5.9.0",
    "pandas>=2.2.0",
    "mmh3",
    "cloud-files",
]

[tool.setuptools.packages.find]
where = ["code"]
